// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXrIdL2RFe8sBFgwh_UmUIaD-EdtJdmyA',
    appId: '1:21675306731:web:71b611efd2e7739c11d8ae',
    messagingSenderId: '21675306731',
    projectId: 'gaga-go',
    authDomain: 'gaga-go.firebaseapp.com',
    storageBucket: 'gaga-go.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUR8c_rD0qA2L2hip3JSJIYswxCTK8y8c',
    appId: '1:21675306731:android:54bb526589dcdf6011d8ae',
    messagingSenderId: '21675306731',
    projectId: 'gaga-go',
    storageBucket: 'gaga-go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0h0v2NWJA_JQHO3qX-EfhedwOIpRq0BY',
    appId: '1:21675306731:ios:fa571078f6cf439711d8ae',
    messagingSenderId: '21675306731',
    projectId: 'gaga-go',
    storageBucket: 'gaga-go.appspot.com',
    iosClientId: '21675306731-aj96ma5r4thiqpngmbjf7sr47rej1dq9.apps.googleusercontent.com',
    iosBundleId: 'com.gagago.gagagonew',
  );
}
